import type { Establishment, Offer, Review, User } from './types';

// 21 Establishments with enhanced properties
export const establishments: Establishment[] = [
  {
    id: 1, name: 'Licorería El Dorado', category: 'licorería',
    description: 'La más amplia selección de licores premium de Los Teques. Contamos con bodegas exclusivas y envíos exprés.',
    lat: 10.3445, lng: -67.0431, address: 'Calle Miranda, Los Teques', phone: '+584145551234', instagram: '@eldoradolt',
    coverImage: '/images/licoreria.png',
    images: ['/images/licoreria.png', '/images/gallery1.png', '/images/offer2.png'],
    avgRating: 4.7, reviewCount: 28, priceRange: '$$', schedule: '10:00 AM - 09:00 PM',
    subRatings: { ambiente: 4.2, servicio: 4.9, precioCalidad: 4.8 },
  },
  {
    id: 2, name: 'Tasca La Cava', category: 'tasca',
    description: 'Ambiente cálido, música acústica en vivo y los cócteles de autor más famosos de la ciudad. Gastronomía gallega y criolla.',
    lat: 10.3482, lng: -67.0389, address: 'Av. Bolívar, Los Teques', phone: '+584145552345', instagram: '@lacavalt',
    coverImage: '/images/tasca.png',
    images: ['/images/tasca.png', '/images/gallery1.png', '/images/offer1.png'],
    avgRating: 4.5, reviewCount: 34, priceRange: '$$', schedule: '12:00 PM - 02:00 AM',
    subRatings: { ambiente: 4.8, servicio: 4.4, precioCalidad: 4.3 },
  },
  {
    id: 3, name: 'Discoteca Eclipse', category: 'discoteca',
    description: 'La mejor pista de baile, espectáculos de luces robóticas y alineación semanal de DJs internacionales de renombre.',
    lat: 10.3411, lng: -67.0456, address: 'Calle Sucre, Los Teques', phone: '+584145553456', instagram: '@eclipselt',
    coverImage: '/images/discoteca.png',
    images: ['/images/discoteca.png', '/images/gallery1.png', '/images/hero.png'],
    avgRating: 4.8, reviewCount: 41, priceRange: '$$$', schedule: '09:00 PM - 05:00 AM',
    subRatings: { ambiente: 4.9, servicio: 4.7, precioCalidad: 4.6 },
  },
  {
    id: 4, name: 'Licorería Premium Select', category: 'licorería',
    description: 'Importación directa y exclusiva de vinos europeos, whiskies añejos y destilados artesanales raros.',
    lat: 10.3501, lng: -67.0402, address: 'Plaza Bolívar, Los Teques', phone: '+584145554567', instagram: '@premiumselectlt',
    coverImage: '/images/licoreria.png',
    images: ['/images/licoreria.png', '/images/gallery1.png', '/images/offer2.png'],
    avgRating: 4.3, reviewCount: 19, priceRange: '$$$', schedule: '11:00 AM - 10:00 PM',
    subRatings: { ambiente: 3.9, servicio: 4.6, precioCalidad: 4.2 },
  },
  {
    id: 5, name: 'Tasca Los Amigos', category: 'tasca',
    description: 'Clásica tasca con deliciosos platos tradicionales venezolanos, cerveza polar bien fría y un ambiente ideal para compartir con panas.',
    lat: 10.3459, lng: -67.0367, address: 'Av. Miranda, Los Teques', phone: '+584145555678', instagram: '@losamigoslt',
    coverImage: '/images/tasca.png',
    images: ['/images/tasca.png', '/images/gallery1.png', '/images/offer1.png'],
    avgRating: 4.6, reviewCount: 52, priceRange: '$', schedule: '11:30 AM - 01:00 AM',
    subRatings: { ambiente: 4.5, servicio: 4.7, precioCalidad: 4.8 },
  },
  {
    id: 6, name: 'Discoteca Noche Eterna', category: 'discoteca',
    description: 'Luces de neón intensas, sistemas de sonido Funktion-One y el mejor ambiente urbano de Los Teques.',
    lat: 10.3398, lng: -67.0491, address: 'Zona Industrial, Los Teques', phone: '+584145556789', instagram: '@nocheeternalt',
    coverImage: '/images/discoteca.png',
    images: ['/images/discoteca.png', '/images/gallery1.png', '/images/hero.png'],
    avgRating: 4.4, reviewCount: 37, priceRange: '$$', schedule: '10:00 PM - 06:00 AM',
    subRatings: { ambiente: 4.6, servicio: 4.1, precioCalidad: 4.3 },
  },
  {
    id: 7, name: 'Licorería Vinos del Valle', category: 'licorería',
    description: 'Especialistas en vinos de altura nacionales e internacionales. Catas privadas todos los fines de semana.',
    lat: 10.3524, lng: -67.0428, address: 'Calle 5, Los Teques', phone: '+584145557890', instagram: '@vinosdelvalle',
    coverImage: '/images/licoreria.png',
    images: ['/images/licoreria.png', '/images/gallery1.png'],
    avgRating: 4.9, reviewCount: 23, priceRange: '$$', schedule: '10:00 AM - 08:00 PM',
    subRatings: { ambiente: 4.8, servicio: 5.0, precioCalidad: 4.8 },
  },
  {
    id: 8, name: 'Tasca El Rincón', category: 'tasca',
    description: 'Auténtico sabor español en Los Teques. Tapas variadas, tortillas y sangría casera artesanal.',
    lat: 10.3473, lng: -67.0445, address: 'Barrio El Carmen, Los Teques', phone: '+584145558901', instagram: '@elrinconlt',
    coverImage: '/images/tasca.png',
    images: ['/images/tasca.png', '/images/gallery1.png'],
    avgRating: 4.2, reviewCount: 29, priceRange: '$$', schedule: '12:00 PM - 12:00 AM',
    subRatings: { ambiente: 4.0, servicio: 4.3, precioCalidad: 4.3 },
  },
  {
    id: 9, name: 'Discoteca La Luna', category: 'discoteca',
    description: 'Un club exclusivo con terraza al aire libre, cócteles premium y una mezcla inigualable de música pop y electrónica.',
    lat: 10.3433, lng: -67.0321, address: 'Av. Principal, Los Teques', phone: '+584145559012', instagram: '@lalunalt',
    coverImage: '/images/discoteca.png',
    images: ['/images/discoteca.png', '/images/gallery1.png'],
    avgRating: 4.7, reviewCount: 44, priceRange: '$$$', schedule: '09:00 PM - 04:00 AM',
    subRatings: { ambiente: 4.8, servicio: 4.6, precioCalidad: 4.5 },
  },
  {
    id: 10, name: 'Licorería Central', category: 'licorería',
    description: 'Tu parada rápida de licores y snacks antes de la fiesta. Ubicación céntrica con estacionamiento vigilado.',
    lat: 10.3468, lng: -67.0472, address: 'Centro Comercial Plaza, Los Teques', phone: '+584145550123', instagram: '@centrallicor',
    coverImage: '/images/licoreria.png',
    images: ['/images/licoreria.png', '/images/gallery1.png'],
    avgRating: 4.1, reviewCount: 16, priceRange: '$', schedule: '09:00 AM - 11:00 PM',
    subRatings: { ambiente: 3.5, servicio: 4.3, precioCalidad: 4.5 },
  },
  {
    id: 11, name: 'Tasca El Sabor', category: 'tasca',
    description: 'Comida familiar de día, tasca animada de noche. Karaoke interactivo y promociones de cervezas.',
    lat: 10.3495, lng: -67.0394, address: 'Calle Real, Los Teques', phone: '+584145551122', instagram: '@elsaborlt',
    coverImage: '/images/tasca.png',
    images: ['/images/tasca.png', '/images/gallery1.png'],
    avgRating: 4.8, reviewCount: 31, priceRange: '$', schedule: '11:00 AM - 02:00 AM',
    subRatings: { ambiente: 4.7, servicio: 4.9, precioCalidad: 4.8 },
  },
  {
    id: 12, name: 'Discoteca Estelar', category: 'discoteca',
    description: 'La discoteca con el diseño más futurista de Miranda. Pistas LED interactivas y palcos VIP de lujo.',
    lat: 10.3402, lng: -67.0513, address: 'Sector La Morita, Los Teques', phone: '+584145552233', instagram: '@estelarlt',
    coverImage: '/images/discoteca.png',
    images: ['/images/discoteca.png', '/images/gallery1.png'],
    avgRating: 4.6, reviewCount: 38, priceRange: '$$$', schedule: '10:00 PM - 05:00 AM',
    subRatings: { ambiente: 4.9, servicio: 4.4, precioCalidad: 4.3 },
  },
  {
    id: 13, name: 'Licorería Oro Negro', category: 'licorería',
    description: 'Selección especializada de rones añejos venezolanos de prestigio e importaciones distinguidas.',
    lat: 10.3517, lng: -67.0419, address: 'Calle 9, Los Teques', phone: '+584145553344', instagram: '@oronegro',
    coverImage: '/images/licoreria.png',
    images: ['/images/licoreria.png', '/images/gallery1.png'],
    avgRating: 4.5, reviewCount: 25, priceRange: '$$', schedule: '10:00 AM - 09:00 PM',
    subRatings: { ambiente: 4.0, servicio: 4.6, precioCalidad: 4.7 },
  },
  {
    id: 14, name: 'Tasca La Parrilla', category: 'tasca',
    description: 'Exquisitas carnes a la parrilla acompañadas de tragos tradicionales y música llanera en vivo los fines de semana.',
    lat: 10.3448, lng: -67.0378, address: 'Av. Los Teques, Los Teques', phone: '+584145554455', instagram: '@laparrillalt',
    coverImage: '/images/tasca.png',
    images: ['/images/tasca.png', '/images/gallery1.png'],
    avgRating: 4.3, reviewCount: 27, priceRange: '$$', schedule: '12:00 PM - 12:00 AM',
    subRatings: { ambiente: 4.3, servicio: 4.2, precioCalidad: 4.4 },
  },
  {
    id: 15, name: 'Discoteca Glamour', category: 'discoteca',
    description: 'Una experiencia inmersiva para los amantes del tech-house y la música urbana. Código de vestimenta elegante.',
    lat: 10.3421, lng: -67.0487, address: 'Zona Rosa, Los Teques', phone: '+584145555566', instagram: '@glamourlt',
    coverImage: '/images/discoteca.png',
    images: ['/images/discoteca.png', '/images/gallery1.png', '/images/offer2.png'],
    avgRating: 4.9, reviewCount: 49, priceRange: '$$$', schedule: '10:00 PM - 06:00 AM',
    subRatings: { ambiente: 5.0, servicio: 4.8, precioCalidad: 4.7 },
  },
  {
    id: 16, name: 'Licorería La Botella', category: 'licorería',
    description: 'Las mejores promociones semanales en cervezas nacionales e importadas. Todo tipo de licores al mejor precio.',
    lat: 10.3489, lng: -67.0435, address: 'Calle Libertador, Los Teques', phone: '+584145556677', instagram: '@labotellalt',
    coverImage: '/images/licoreria.png',
    images: ['/images/licoreria.png', '/images/gallery1.png'],
    avgRating: 4.0, reviewCount: 14, priceRange: '$', schedule: '09:00 AM - 10:00 PM',
    subRatings: { ambiente: 3.3, servicio: 4.2, precioCalidad: 4.6 },
  },
  {
    id: 17, name: 'Tasca El Patio', category: 'tasca',
    description: 'Un jardín colonial reformado en tasca. Excelente coctelería tropical, pizzas a la leña y acústicos los viernes.',
    lat: 10.3452, lng: -67.0354, address: 'Plaza Sucre, Los Teques', phone: '+584145557788', instagram: '@elpatio',
    coverImage: '/images/tasca.png',
    images: ['/images/tasca.png', '/images/gallery1.png'],
    avgRating: 4.7, reviewCount: 33, priceRange: '$$', schedule: '06:00 PM - 01:00 AM',
    subRatings: { ambiente: 4.9, servicio: 4.6, precioCalidad: 4.5 },
  },
  {
    id: 18, name: 'Discoteca Vibra', category: 'discoteca',
    description: 'El templo de los ritmos latinos, reggaetón de la vieja escuela y noches temáticas emocionantes.',
    lat: 10.3419, lng: -67.0463, address: 'Av. Miranda Este, Los Teques', phone: '+584145558899', instagram: '@vibralt',
    coverImage: '/images/discoteca.png',
    images: ['/images/discoteca.png', '/images/gallery1.png'],
    avgRating: 4.4, reviewCount: 22, priceRange: '$$', schedule: '09:00 PM - 05:00 AM',
    subRatings: { ambiente: 4.5, servicio: 4.2, precioCalidad: 4.4 },
  },
  {
    id: 19, name: 'Licorería Selecta', category: 'licorería',
    description: 'Un espacio boutique elegante con la mayor colección de licores importados exclusivos y asesoramiento personalizado.',
    lat: 10.3531, lng: -67.0398, address: 'Calle 12, Los Teques', phone: '+584145559900', instagram: '@selectalt',
    coverImage: '/images/licoreria.png',
    images: ['/images/licoreria.png', '/images/gallery1.png'],
    avgRating: 4.6, reviewCount: 18, priceRange: '$$$', schedule: '10:00 AM - 09:00 PM',
    subRatings: { ambiente: 4.3, servicio: 4.8, precioCalidad: 4.4 },
  },
  {
    id: 20, name: 'Tasca La Esquina', category: 'tasca',
    description: 'El lugar perfecto para tomar algo después del trabajo. Excelente surtido de picoteo y jarras de sangría heladas.',
    lat: 10.3479, lng: -67.0411, address: 'Esquina El Carmen, Los Teques', phone: '+584145550099', instagram: '@laesquinalt',
    coverImage: '/images/tasca.png',
    images: ['/images/tasca.png', '/images/gallery1.png'],
    avgRating: 4.2, reviewCount: 21, priceRange: '$', schedule: '04:00 PM - 12:00 AM',
    subRatings: { ambiente: 4.1, servicio: 4.1, precioCalidad: 4.3 },
  },
  {
    id: 21, name: 'Discoteca Royal', category: 'discoteca',
    description: 'Elegancia nocturna sin límites. Zonas VIP privadas, barras premium, y los espectáculos artísticos más atrevidos del estado.',
    lat: 10.3395, lng: -67.0505, address: 'Sector Los Rosales, Los Teques', phone: '+584145551188', instagram: '@royallt',
    coverImage: '/images/discoteca.png',
    images: ['/images/discoteca.png', '/images/gallery1.png', '/images/hero.png'],
    avgRating: 4.8, reviewCount: 36, priceRange: '$$$', schedule: '10:00 PM - 06:00 AM',
    subRatings: { ambiente: 5.0, servicio: 4.7, precioCalidad: 4.6 },
  },
];

export const offers: Offer[] = [
  { id: 1, establishmentId: 1, title: 'Whisky Premium 18 años', description: 'Botella de 750ml. Reserva limitada de malta única.', price: '$89', discount: '20% OFF', image: '/images/offer2.png', code: 'GOLD18' },
  { id: 2, establishmentId: 2, title: 'Cóctel Noche Dorada', description: 'Gin premium + tónica especial + infusión de cítricos.', price: '$12', discount: '2x1', image: '/images/offer1.png', code: 'CAVA2X1' },
  { id: 3, establishmentId: 3, title: 'Botella de Champagne', description: 'Veuve Clicquot Brut 750ml helada con copa VIP.', price: '$75', discount: 'PROMO VIP', image: '/images/offer2.png', code: 'ECLIPSEVIP' },
  { id: 4, establishmentId: 5, title: 'Ron Añejo + 2 Raciones', description: 'Combo especial con ración de tequeños y empanaditas.', price: '$28', discount: 'POPULAR', image: '/images/offer1.png', code: 'AMIGOSPACK' },
  { id: 5, establishmentId: 15, title: 'Entrada VIP + 2 bebidas', description: 'Acceso preferente sin cola + 2 cócteles a elección.', price: '$35', discount: 'EXCLUSIVO', image: '/images/offer2.png', code: 'GLAMOURVIP' },
];

export const initialReviews: Review[] = [
  { id: 1, establishmentId: 1, userId: 'u1', userName: 'Carlos Mendoza', userAvatar: 'https://i.pravatar.cc/40?img=12', rating: 5, comment: 'Excelente selección de whiskies. La atención de su personal es de primera, te asesoran muy bien.', date: '2026-07-20' },
  { id: 2, establishmentId: 2, userId: 'u2', userName: 'María López', userAvatar: 'https://i.pravatar.cc/40?img=28', rating: 5, comment: 'La mejor música acústica en vivo de Los Teques. El ambiente es super íntimo, ideal para parejas.', date: '2026-07-25' },
  { id: 3, establishmentId: 3, userId: 'u3', userName: 'Jean Gómez', userAvatar: 'https://i.pravatar.cc/40?img=33', rating: 5, comment: 'El juego de luces y el sonido en este local son de otro planeta. Definitivamente volveré.', date: '2026-07-28' },
];

// Simulated Google user
export const mockGoogleUser: User = {
  id: 'currentUser',
  name: 'Ana Rodríguez',
  email: 'ana.rodriguez@gmail.com',
  avatar: 'https://i.pravatar.cc/40?img=47',
};
