// ─────────────────────────────────────────────────────────────
// CONECTA-LT 3.0 — Reservation Service Layer
// Orchestrates the persistent reservation flow:
//
//   - createReservation   → INSERT reservation + (optional) link coupon
//                            inside a single Prisma transaction.
//   - listMyReservations  → user-scoped list (ordered by date asc).
//   - cancelReservation   → flip status to CANCELLED + (optional) revert
//                            the linked coupon back to CLAIMED, inside a
//                            single transaction so the two never drift.
//
// Errors are thrown as `Response` objects (same convention as
// promotion.service.ts / review.service.ts) so route handlers can
// propagate them with `if (e instanceof Response) return e;`.
// ─────────────────────────────────────────────────────────────

import { db } from '@/lib/db';
import {
  reservationRepository,
  type ReservationWithRelations,
} from '@/server/repositories/reservation.repository';

/**
 * Build a JSON Response (thrown from service → returned by route handler).
 * Throwing a Response is the same convention used by `requireUser()`.
 */
function jsonError(message: string, status: number): Response {
  return new Response(JSON.stringify({ error: message }), {
    status,
    headers: { 'content-type': 'application/json' },
  });
}

// ── Validation helpers ──────────────────────────────────────

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const TIME_RE = /^\d{2}:\d{2}$/;

/**
 * Validate a "YYYY-MM-DD" string is a real calendar date.
 *
 * A regex alone isn't enough — "2025-13-45" would pass `\d{4}-\d{2}-\d{2}`
 * but isn't a valid date. We round-trip through `Date.UTC` and verify the
 * components match so "2025-02-31" (which JS silently rolls over to
 * March 3rd) is rejected.
 */
function isValidDate(s: string): boolean {
  if (!DATE_RE.test(s)) return false;
  const parts = s.split('-');
  const y = Number(parts[0]);
  const m = Number(parts[1]);
  const d = Number(parts[2]);
  if (!Number.isInteger(y) || !Number.isInteger(m) || !Number.isInteger(d)) {
    return false;
  }
  if (m < 1 || m > 12) return false;
  if (d < 1 || d > 31) return false;
  const dt = new Date(Date.UTC(y, m - 1, d));
  return (
    dt.getUTCFullYear() === y &&
    dt.getUTCMonth() === m - 1 &&
    dt.getUTCDate() === d
  );
}

/**
 * Validate a "HH:mm" 24h string. Hours 00-23, minutes 00-59.
 */
function isValidTime(s: string): boolean {
  if (!TIME_RE.test(s)) return false;
  const parts = s.split(':');
  const h = Number(parts[0]);
  const m = Number(parts[1]);
  if (!Number.isInteger(h) || !Number.isInteger(m)) return false;
  if (h < 0 || h > 23) return false;
  if (m < 0 || m > 59) return false;
  return true;
}

/**
 * Generate a confirmation code matching the frontend's
 * `generateReservationCode()` in src/lib/store.ts:
 *
 *   "LT-" + 4 random digits (1000-9999) + "-" + 1 random A-Z letter
 *
 * Examples: "LT-4827-K", "LT-9931-Q".
 *
 * Mirrored server-side so codes generated by the API look identical to
 * the ones the (now-superseded) client-side mock used to produce.
 */
function generateConfirmationCode(): string {
  return (
    'LT-' +
    Math.floor(1000 + Math.random() * 9000) +
    '-' +
    String.fromCharCode(65 + Math.floor(Math.random() * 26))
  );
}

/**
 * Generate a confirmation code and retry up to 5 times if the generated
 * code already exists in the DB (collision on the unique
 * `confirmationCode` constraint).
 *
 * With a 4-digit + 1-letter namespace (~360k codes) collisions are
 * astronomically unlikely at the volumes this app handles, but the
 * pre-check guarantees we never throw P2002 on the INSERT path.
 */
async function generateUniqueConfirmationCode(): Promise<string> {
  for (let attempt = 0; attempt < 5; attempt++) {
    const code = generateConfirmationCode();
    const existing = await reservationRepository.findByConfirmationCode(code);
    if (!existing) return code;
  }
  // 5 collisions in a row → astronomically unlikely; surface a 500.
  throw jsonError(
    'No se pudo generar un código de confirmación único. Intenta de nuevo.',
    500,
  );
}

// ── Public types ────────────────────────────────────────────

/**
 * Public shape returned by `createReservation`. The route handler
 * returns this verbatim as the 201 JSON body.
 *
 *   - `reservation`        — the freshly created reservation, with the
 *                            minimal business payload + the linked
 *                            couponRedemption (if any).
 *   - `confirmationCode`   — convenience field mirroring
 *                            `reservation.confirmationCode` so the
 *                            client can display it without digging
 *                            into the nested object (e.g. for a
 *                            "tu código es X" toast).
 */
export type CreateReservationResult = {
  reservation: {
    id: string;
    confirmationCode: string;
    status: string;
    date: string;
    time: string;
    guests: number;
    notes: string | null;
    name: string;
    phone: string;
    email: string | null;
    business: {
      id: string;
      name: string;
      slug: string;
      address: string;
      coverImage: string | null;
      phone: string | null;
    };
    couponRedemption: {
      id: string;
      status: string;
      promotion: {
        id: string;
        title: string;
        code: string | null;
        image: string | null;
        discount: string | null;
        price: string | null;
      };
    } | null;
  };
  confirmationCode: string;
};

/**
 * Public shape returned by `listMyReservations`. Each entry carries
 * the minimal business payload (so the UI can link to the detail page)
 * + the linked coupon info (code/title/image/discount) so the UI can
 * show "Cupón: SANCHO18 — 20% OFF" inline.
 *
 * `coupon` is `null` when the reservation was made without a coupon.
 */
export type MyReservationEntry = {
  id: string;
  confirmationCode: string;
  status: string;
  date: string;
  time: string;
  guests: number;
  notes: string | null;
  name: string;
  phone: string;
  createdAt: string;
  business: {
    id: string;
    name: string;
    slug: string;
    address: string;
    coverImage: string | null;
    phone: string | null;
  };
  coupon: {
    code: string | null;
    title: string;
    image: string | null;
    discount: string | null;
  } | null;
};

export const reservationService = {
  /**
   * Create a new reservation for the authenticated user.
   *
   * Validation flow (each throws a 4xx Response on failure):
   *   1. 404 "Negocio no encontrado"      if the business slug doesn't match
   *   2. 400 "Fecha u hora inválida"      if date/time format is wrong
   *   3. 400 "Número de comensales inválido" if guests is not an integer >= 1
   *   4. 400 "Nombre requerido"           if name is empty after trim
   *   5. 400 "Teléfono requerido"         if phone is empty after trim
   *   6. (optional) 404 "Cupón no encontrado"     if couponRedemptionId
   *                  doesn't exist or belongs to another user
   *      (optional) 400 "Este cupón ya fue usado" if its status !== 'CLAIMED'
   *
   * Atomic write flow inside a single Prisma transaction:
   *   a. (optional) re-validate the couponRedemption inside the tx
   *      (so the status check is consistent with the eventual write).
   *   b. create(data, tx) — inserts the Reservation row in PENDING status.
   *   c. (optional) linkCouponRedemption(reservation.id, couponRedemptionId, tx)
   *      — flips the coupon from CLAIMED → USED and stamps `usedAt = now()`,
   *      and ties it 1:1 to the new reservation.
   *   d. (optional) re-fetch the reservation by id so the response carries
   *      the now-linked couponRedemption (the `create` payload returned
   *      before step (c) wouldn't include it).
   *
   * Both/all writes commit together or roll back together, so the coupon
   * can never be marked USED without a corresponding reservation row.
   */
  createReservation: async (
    userId: string,
    input: {
      businessSlug: string;
      name: string;
      phone: string;
      email?: string | null;
      date: string;
      time: string;
      guests: number | string;
      notes?: string | null;
      couponRedemptionId?: string | null;
    },
  ): Promise<CreateReservationResult> => {
    // ── 1. Validate business by slug ───────────────────────────────
    // Minimal select — we only need the id; full business payload is
    // fetched lazily via the reservationInclude on the response path.
    const business = await db.business.findUnique({
      where: { slug: input.businessSlug },
      select: { id: true },
    });
    if (!business) {
      throw jsonError('Negocio no encontrado', 404);
    }

    // ── 2. Validate date (YYYY-MM-DD) + time (HH:mm) ───────────────
    if (!isValidDate(input.date) || !isValidTime(input.time)) {
      throw jsonError('Fecha u hora inválida', 400);
    }

    // ── 3. Validate guests (integer >= 1) ──────────────────────────
    // Accept either a number or a numeric string (the frontend's
    // BookingData stores guests as a string from the input field).
    const guestsNum =
      typeof input.guests === 'string'
        ? Number.parseInt(input.guests, 10)
        : input.guests;
    if (!Number.isInteger(guestsNum) || guestsNum < 1) {
      throw jsonError('Número de comensales inválido', 400);
    }

    // ── 4. Validate name (non-empty after trim) ────────────────────
    const trimmedName = (input.name ?? '').trim();
    if (!trimmedName) {
      throw jsonError('Nombre requerido', 400);
    }

    // ── 5. Validate phone (non-empty after trim) ───────────────────
    const trimmedPhone = (input.phone ?? '').trim();
    if (!trimmedPhone) {
      throw jsonError('Teléfono requerido', 400);
    }

    // Normalize optional string fields: empty/whitespace → null.
    const email =
      typeof input.email === 'string' && input.email.trim().length > 0
        ? input.email.trim()
        : null;
    const notes =
      typeof input.notes === 'string' && input.notes.trim().length > 0
        ? input.notes.trim()
        : null;
    const couponRedemptionId =
      typeof input.couponRedemptionId === 'string' &&
      input.couponRedemptionId.trim().length > 0
        ? input.couponRedemptionId.trim()
        : null;

    // ── 6. Generate unique confirmation code ───────────────────────
    // Done OUTSIDE the transaction (the uniqueness check is a read on
    // the singleton client; the unique constraint is the final guard
    // inside the tx).
    const confirmationCode = await generateUniqueConfirmationCode();

    // ── 7. Atomic write: create reservation + (optional) link coupon
    const reservation = await db.$transaction(async (tx) => {
      // Re-validate the coupon inside the tx so the status check is
      // consistent with the eventual `linkCouponRedemption` write
      // (avoids the race where another reservation consumes the coupon
      // between the pre-check and the link).
      if (couponRedemptionId) {
        const redemption =
          await reservationRepository.findCouponRedemptionByUser(
            couponRedemptionId,
            userId,
            tx,
          );
        if (!redemption) {
          throw jsonError('Cupón no encontrado', 404);
        }
        if (redemption.status !== 'CLAIMED') {
          throw jsonError('Este cupón ya fue usado', 400);
        }
      }

      const created = await reservationRepository.create(
        {
          confirmationCode,
          businessId: business.id,
          userId,
          name: trimmedName,
          phone: trimmedPhone,
          email,
          date: input.date,
          time: input.time,
          guests: guestsNum,
          notes,
        },
        tx,
      );

      if (couponRedemptionId) {
        await reservationRepository.linkCouponRedemption(
          created.id,
          couponRedemptionId,
          tx,
        );
        // Re-fetch so the response carries the now-linked
        // couponRedemption (the `create` payload returned above was
        // assembled before the link write, so its couponRedemption
        // field would be null).
        const refreshed = await reservationRepository.findById(created.id, tx);
        if (!refreshed) {
          // Should never happen — we just created the row a few lines up.
          throw jsonError('Error interno del servidor', 500);
        }
        return refreshed;
      }

      return created;
    });

    // ── 8. Build the response payload ──────────────────────────────
    return {
      reservation: {
        id: reservation.id,
        confirmationCode: reservation.confirmationCode,
        status: reservation.status,
        date: reservation.date,
        time: reservation.time,
        guests: reservation.guests,
        notes: reservation.notes,
        name: reservation.name,
        phone: reservation.phone,
        email: reservation.email,
        business: {
          id: reservation.business.id,
          name: reservation.business.name,
          slug: reservation.business.slug,
          address: reservation.business.address,
          coverImage: reservation.business.coverImage,
          phone: reservation.business.phone,
        },
        couponRedemption: reservation.couponRedemption
          ? {
              id: reservation.couponRedemption.id,
              status: reservation.couponRedemption.status,
              promotion: {
                id: reservation.couponRedemption.promotion.id,
                title: reservation.couponRedemption.promotion.title,
                code: reservation.couponRedemption.promotion.code,
                image: reservation.couponRedemption.promotion.image,
                discount: reservation.couponRedemption.promotion.discount,
                price: reservation.couponRedemption.promotion.price,
              },
            }
          : null,
      },
      confirmationCode: reservation.confirmationCode,
    };
  },

  /**
   * List all reservations for the authenticated user, ordered by
   * `date` ascending (so the next upcoming reservation floats to the
   * top — the UI renders them in chronological order).
   *
   * Returns: Array<MyReservationEntry>
   *
   * NOTE: cancelled / completed / no-show reservations are included
   * too — the UI uses the `status` field to render them with the
   * appropriate badge. The user's full reservation history matters
   * more than filtering by status here.
   */
  listMyReservations: async (
    userId: string,
  ): Promise<MyReservationEntry[]> => {
    const reservations = await reservationRepository.listByUser(userId);
    return reservations.map((r: ReservationWithRelations) => ({
      id: r.id,
      confirmationCode: r.confirmationCode,
      status: r.status,
      date: r.date,
      time: r.time,
      guests: r.guests,
      notes: r.notes,
      name: r.name,
      phone: r.phone,
      createdAt: r.createdAt.toISOString(),
      business: {
        id: r.business.id,
        name: r.business.name,
        slug: r.business.slug,
        address: r.business.address,
        coverImage: r.business.coverImage,
        phone: r.business.phone,
      },
      coupon: r.couponRedemption
        ? {
            code: r.couponRedemption.promotion.code,
            title: r.couponRedemption.promotion.title,
            image: r.couponRedemption.promotion.image,
            discount: r.couponRedemption.promotion.discount,
          }
        : null,
    }));
  },

  /**
   * Cancel a reservation owned by the authenticated user.
   *
   * Validation flow (each throws a 4xx Response on failure):
   *   1. 404 "Reserva no encontrada"            if the id doesn't match
   *   2. 403 "No tienes permiso para cancelar esta reserva"
   *                                              if reservation.userId !== userId
   *   3. 400 "Esta reserva ya no puede cancelarse"
   *                                              if status not in {PENDING, CONFIRMED}
   *
   * Atomic write flow inside a single Prisma transaction:
   *   a. updateStatus(reservation.id, 'CANCELLED', tx)
   *   b. (optional) unlinkCouponRedemption(couponRedemption.id, tx)
   *      — clears reservationId, reverts status to CLAIMED,
   *        and clears usedAt, so the user can use the coupon again
   *        on a future reservation.
   *
   * Both writes commit together or roll back together, so the coupon
   * is never left in USED state while the reservation is CANCELLED
   * (or vice versa).
   *
   * Returns `{ reservation: { id, status } }` — minimal payload since
   * the UI typically only needs the new status to update its local cache.
   */
  cancelReservation: async (
    userId: string,
    reservationId: string,
  ): Promise<{ reservation: { id: string; status: string } }> => {
    // ── 1. Find the reservation ────────────────────────────────────
    const reservation = await reservationRepository.findById(reservationId);
    if (!reservation) {
      throw jsonError('Reserva no encontrada', 404);
    }

    // ── 2. Ownership check ─────────────────────────────────────────
    if (reservation.userId !== userId) {
      throw jsonError(
        'No tienes permiso para cancelar esta reserva',
        403,
      );
    }

    // ── 3. Status check (only PENDING / CONFIRMED can be cancelled) ─
    if (
      reservation.status !== 'PENDING' &&
      reservation.status !== 'CONFIRMED'
    ) {
      throw jsonError('Esta reserva ya no puede cancelarse', 400);
    }

    // ── 4. Atomic: cancel + (optional) unlink coupon ───────────────
    await db.$transaction(async (tx) => {
      await reservationRepository.updateStatus(
        reservation.id,
        'CANCELLED',
        tx,
      );
      if (reservation.couponRedemption) {
        await reservationRepository.unlinkCouponRedemption(
          reservation.couponRedemption.id,
          tx,
        );
      }
    });

    return {
      reservation: { id: reservation.id, status: 'CANCELLED' },
    };
  },
};
